import jsonschema from 'jsonschema';

const Validator = jsonschema.Validator;
const v = new Validator();

// This seed data is used to populate the database with music events, artists, and tracks
const data = {
  events: [
    {
      name: 'Electronic Daisy Carnival',
      year: '2016',
      days: 3,
      ref: 'EDC',
      artists: [
        '12th Planet',
        '219 Boys',
        '4B',
        'A-Trak',
        'Above & Beyond',
        'Ace Ventura',
        'Adrenalize',
        'Adventure Club',
        'Afrojack',
        'Alan Fitzpatrick',
        'Alesso',
        'Alison Wonderland',
        'Aly & Fila',
        'Amtrac',
        'Andy C',
        'Anevo',
        'Angerfist',
        'Anna Lunoe',
        'Armand Van Helden',
        'Armanni Reign',
        'Armin Van Buuren',
        'Aryay',
        'Astrix',
        'Astronomar',
        'Teddy Killerz',
        'Audiofreq',
        'Audiotricz',
        'Awe',
        'Axwell /\\ Ingrosso',
        'Bad Boy Bill',
        'Bad Company UK',
        'Baggi',
        'Bart Skils',
        'Baumer',
        'Ben Nicky',
        'Billy Kenny',
        'Bioweapon',
        'Bones',
        'Bot',
        'Botnek',
        'Brennan Heart',
        'Brennen Grey',
        'Brillz',
        'Bro Safari',
        'Brookes Brothers',
        'Carnage',
        'Rusko',
        'Chadwick',
        'The Chainsmokers',
        'Chris Lake',
        'Chris Liebing',
        'Chris Lorenzo',
        'Code Black',
        'Cookie Monsta',
        'Coone',
        'Coyote Kisses',
        'Craig Williams',
        'Crisis Era',
        'Crizzly',
        'Culture Shock',
        'Cyantific',
        'Da Tweekaz',
        'Dada Life',
        'Danny Howard',
        'Darksiderz',
        'Darren Styles',
        'Dash Berlin',
        'Datsik',
        'Dela Moontribe',
        'Delta Heavy',
        'Deorro',
        'Des Mcmahon',
        'Dimitri Vegas & Like Mike',
        'DJ Isaac',
        'DJ Dan',
        'DJ Snake',
        'DJ Trance',
        'Doc Martin',
        'Doctor P',
        'Don Diablo',
        'Dr. Fresch',
        'Duke Dumont',
        'Dusky',
        'El Dusty',
        'Ephwurd',
        'Eptic',
        'Must Die!',
        'Eric Prydz',
        'Etnik',
        'Excision',
        'Ferry Corsten',
        'Fester',
        'Flux Pavilion',
        'Frankee',
        'Loadstar',
        'Frankie Bones',
        'Funtcase',
        'Fury',
        'Gaia',
        'Galantis',
        'Gammer',
        'Gareth Emery',
        'Giraffage',
        'Gladiator',
        'Go Freek',
        'GTA',
        'Gunz For Hire',
        'Habstrakt',
        'Habu',
        'Hannah Wants',
        'Hardwell',
        'Hermitude',
        'Hot Since 82',
        'Hotel Garuda',
        'InsideInfo',
        'J. Phlip',
        'Jason Bentley',
        'Jauz',
        'John Askew',
        'John Kelley',
        'John O\'Callaghan',
        'Jordan Suckley',
        'Joyryde',
        'Jstjr',
        'Juan Atkins',
        'Julia Govor',
        'Julian Jordan',
        'Kaskade',
        'Kasra',
        'Kdrew',
        'Knife Party',
        'Krne',
        'Kshmr',
        'Kutski',
        'Lady Faith',
        'Landis Lapace',
        'Lane 8',
        'Lenny Dee',
        'Lione',
        'LNY TNZ',
        'Loco Dice',
        'LondonBridge',
        'Lookas',
        'LoudPvck',
        'LUMBERJVCK',
        'Makj',
        'Mark Farina',
        'Markus Schulz',
        'Marshmello',
        'Martin Garrix',
        'Martin Solveig',
        'Matrix & Futurebound',
        'Matt Black',
        'Max Enforcer',
        'Maximono',
        'MC DINO',
        'Mefjus',
        'Mekanikal',
        'Mercer',
        'Michael Calfan',
        'Mike Williams',
        'Morten',
        'My Digital Enemy',
        'NGHTMRE',
        'Nicole Moudaber',
        'Nightstalker',
        'Oliver Heldens',
        'Ookay',
        'Pan-pot',
        'Paper Diamond',
        'Party Favor',
        'Paul Oakenfold',
        'Paul Ritch',
        'Paul Van Dyk',
        'Pendulum',
        'Pierce Fulton',
        'Pilo',
        'Protohype',
        'Radical Redemption',
        'Ran-D',
        'Ravell',
        'Redlight',
        'Rell the Soundbender',
        'Richie Hawtin',
        'RL Grime',
        'Rob Gee',
        'Ron D Core',
        'Sacha Robotti',
        'Seven Lions',
        'Shaun Frank',
        'Shiba San',
        'Slander',
        'Sleepy Tom',
        'Sluggers',
        'Snails',
        'Snbrn',
        'Sonny Fodera',
        'Stephanie',
        'Steve Loria',
        'Suspect 44',
        'Sylence',
        'Taiki Nulight',
        'Technoboy',
        'The Chainsmokers',
        'The Magician',
        'The Prototypes',
        'Thee-O',
        'Throttle',
        'Tiësto',
        'TJR',
        'TNT',
        'Tom & Collins',
        'Tommy Trash',
        'Totally Enormous Extinct Dinosaurs',
        'Jonas Rathsman',
        'Trollphace',
        'Troyboi',
        'Tuneboy',
        'Two Fresh',
        'Tycho',
        'Umek',
        'Valentino Khan',
        'W&W',
        'Walker & Royce',
        'Wasted Penguinz',
        'What So Not',
        'Wuki',
        'Yellow Claw',
        'Zander',
        'Zedd',
        'Zomboy',
      ],
    },
    {
      name: 'Hard Summer',
      year: '2016',
      days: 2,
      ref: 'HS',
      artists: [
        'Porter Robinson',
        'Tchami',
      ]
    }
  ],
};

const devoData = {
  events: [
    {
      name: 'Electronic Daisy Carnival',
      year: '2016',
      days: 3,
      ref: 'EDC',
      artists: [
        '12th Planet',
        '219 Boys',
      ],
    },
    {
      name: 'Hard Summer',
      year: '2016',
      days: 2,
      ref: 'HS',
      artists: [
        'Porter Robinson',
        'Tchami',
      ]
    }
  ],
};

// Represents the data variable above, for schema validation
const dataSchema = {
  id: '/DataSchema',
  type: 'object',
  properties: {
    events: { type: 'array', items: { type: 'object', $ref: '/EventSchema' } },
  },
  required: ['events'],
};

// Represents the list of events
const eventSchema = {
  id: '/EventSchema',
  type: 'object',
  properties: {
    name: { type: 'string' },
    year: { type: 'string' },
    days: { type: 'number' },
    ref: { type: 'string' },
    artists: { type: 'array', items: { type: 'string' } },
  },
  required: ['name', 'year', 'days', 'ref', 'artists'],
};

v.addSchema(eventSchema, '/EventSchema');

// Validate data against the dataSchema and returns ValidationResult list
function validate(data) {
  return v.validate(data, dataSchema);
}

export default {
  devoData,
  data,
  validator: {
    validate
  }
}
